name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Run golang tests
        run: go test


  doctest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build docs
        run: |
          pandoc ./README.md --output=./docs/index.html \
            --css=https://cdn.simplecss.org/simple.min.css \
            --metadata=title=${APP} --standalone
          go run . export --resume=./docs/resume.json \
            --html-output=docs/simple.html --pdf=false
          go run . export --resume=./docs/resume.json \
            --html-theme=simple-compact --html-output=./docs/simple-compact.html \
            --pdf=false
          go run . export --resume=./docs/resume.json \
            --html-theme=actual --html-output=./docs/actual.html \
            --pdf-theme=actual --pdf-output=./docs/actual.pdf

